### PR TITLE
Move global config to local

### PR DESCRIPTION
**Pull request by vvb2060**
This allows others to not have to configure busybox module.

### CODE REVIEW

**Comment by osm0sis** [comment]
Wouldn't LOCAL_SHORT_COMMANDS also be needed to avoid slow toybox builds? If you need to make it local for some reason then it should probably be in both busybox.mk and toybox.mk. 👍

**Comment by vvb2060** [comment]
I didn't test toybox, I think it doesn't reach the command line length limit for Windows. Does it really need this flag?

**Comment by osm0sis** [comment]
I've never compiled toybox either, so would have to test to be certain, but it has well over 150 files to build so I think it would have the same problem as busybox on Windows NDK.

**Comment by vvb2060** [comment]
I have tested the 1.33.1 branch of busybox on Windows 10 using powershell and the build is fine. I think the flag can be removed.

**Comment by osm0sis** [comment]
I added the flag here because the NDK on my machine in Command Prompt warned about the long names and the long compile time. I don't think anything has changed in busybox or the Windows NDK that would resolve this, so it's still an issue, but even if so, especially for those using older NDK this is useful and not harming anything.

**Comment by osm0sis** [comment]
You were the one who added the same fix to Magisk: https://github.com/topjohnwu/Magisk/commit/b90c65370effdf4e1fb87effd1d8bd6e60172528

Same issue here. Only it's better to ifdef it since only Windows really needs it to not be slowed down.

**Comment by vvb2060** [comment]
Yes, in later versions, busybox may reach the command line length limit again at any time, so I'm keeping this PR unchanged. toybox has far fewer files than busybox (toybox Android_src.mk 3.3KiB vs busybox Android_src.mk  13KiB), so I don't think it needs this flag.

https://devblogs.microsoft.com/oldnewthing/20031210-00/?p=41553

**Pull request merged**
