### PR TITLE
Update for BusyBox 1.34.1, Fix build for latest pcre2, Fix UB from clang busybox optimization

### PR DESCRIPTION
**Pull request by osm0sis**
Update for BusyBox 1.34.1
- remove upstreamed patches
- combine leftover hush platform patches
- rebase patches over released stable 1.34.1

Fix build for latest pcre2
- update external.mk for pcre2 source reorganization
- work around a new symlink from .c -> .c.dist which can break NDK compiles on Windows

Fix UB from clang busybox optimization
- see https://github.com/topjohnwu/Magisk/pull/4731
- thanks @yujincheng08 and @canyie for the upstream busybox patches

### CODE REVIEW

**Comment by osm0sis** [comment]
Just noticed and updated the new tag variable you added in run.sh to 1_34_stable :+1:

It can later be updated to 1_34_1 once Denys realizes he missed making the tag and adds it. 😛

**Comment by osm0sis** [comment]
Aaand pcre2 was updated yesterday, so I'll fix that as well.

**Comment by osm0sis** [comment]
The tag is fixed now. I'll update this again.

**Comment by osm0sis** [comment]
Good to go again!

**Comment by abgdia5969** [comment]
masih xpaham lagi..aduhh pening kpala weh..ajar sya sat

**Review by topjohnwu — APPROVED** [review]

**Pull request merged**
