### PR TITLE
Implement common script for busybox and toybox

### PR DESCRIPTION
**Pull request by ghost**
* handle the patches efficiently
* handle error and also spam of git if no config found
* handle busybox and toybox using a single script
and a helper script

output when i ran the script on latest busybox:
```
root@kali:~/ndk-box-kitchen# python3 ndk-box.py --target busybox  --patch --generate --commit

Applying busybox patches for ndk-build


The following patches applied successfully:
0001-Fix-mconf-lkc-host-warning-statement-with-no-effect.patch
0002-android-fix-mount-umount-fsck-df.patch
0003-eject-add-missing-headers.patch
0004-fix-udhcpd-and-nameif-add-ether_ntoa_r-and-ether_ato.patch
0005-fix-ether-wake-avoid-ether_hostton-and-include-if_et.patch
0006-loadfont-setfont-conspy-add-missing-header.patch
0007-android-syscalls-shmget-msgget-semget.patch
0008-android-syscalls-msgctl-shmctl.patch
0009-android-syscalls-shmdt-shmat-sembuf.patch
0010-android-syscall-non-trivial-semctl.patch
0011-missing_syscalls-semctl-fix-missing-definitions-on-x.patch
0012-fix-ipcs-ipcrm-no-sys-sem-shm-msg-etc.patch
0013-fix-syslogd-logread-add-syslog.h-semop-shmdt-at.patch
0014-fix-fsck.minix-mkfs.minix-undef-HAVE_SETBIT-MINIX2_S.patch
0015-fix-ipv6-add-ipv6_route.h.patch
0016-additional-fix-up-for-IPV6-on-Android-API-21.patch
0017-fix-udhcpc6-add-missing-ifaddrs.h-and-getifaddrs-fre.patch
0019-platform-minor-adjustments-to-support-unified-header.patch
0020-fix-hush-add-glob-and-sigisemptyset.patch
0021-glob-minor-adjustments-to-support-unified-headers.patch
0022-modinfo-modprobe-use-ifdef-block-for-android-without.patch
0023-depmod-fix-syntax-with-modules-in-parameter.patch
0024-fix-reboot-poweroff-hack-android_reboot-support.patch
0025-fix-tls-avoid-problematic-ASM-code-only-triggered-by.patch
0026-fix-nslookup-add-libres-a-dietlibc-resolver.patch
0027-hack-use-dietlibc-s-resolver-to-avoid-static-compili.patch
0028-dietlibc-dnscruft-try-to-get-dns-server-via-command-.patch
0029-ash-history.patch
0030-Remove-unnecessary-missing-syscalls.patch
0031-Add-runtime-toggle-to-enable-standalone-ash.patch
0032-Disable-SELinux-features-for-install.patch
0033-Allow-running-as-libbusybox.so.patch

The following patches failed to apply:
0018-fix-time-hush-add-missing-definitions-on-Android-API.patch

Generating configuration files for busybox


Generating Android_src.mk based on busybox configs


commit patches and generated Makefiles of busybox for ndk-build

[master 90f4e4d] busybox: Add generated files for ndk-build
 2 files changed, 583 insertions(+)
 create mode 100644 Android.mk
 create mode 100644 Android_src.mk
```

Screenshot_20210713-222411

I am currently learning python3. made these changes as a practice. thought it will be helpful. ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by osm0sis** [comment]
I feel like your --target and --src_path additions might just be overcomplicating things needlessly.. it certainly feels much easier to just be able to run the appropriate script with the simple commands and one-word arguments.

By the way, that patch failed to apply probably because you hadn't checked out 1.33.1 per the README.

**Comment by ghost** [comment]
> I feel like your --target and --src_path additions might just be overcomplicating things needlessly.. it certainly feels much easier to just be able to run the appropriate script with the simple commands and one-word arguments.
> 
> By the way, that patch failed to apply probably because you hadn't checked out 1.33.1 per the README.

i have removed the unnecessary src_path argparse. it will use the same path as it was using
before.

--target is required to determine what to patch, generate, commit

i just wanted to make all things in one script
and make things debug easily(applied patch and failed patch in case of bringup) and handle the errors efficiently

and the failed patch, i just tried on 1.34 to give a demo

**Comment by osm0sis** [comment]
Thanks for fixing that. As for everything else, it's all up to @topjohnwu, and since this would affect Magisk builds as well would need changes over there too. 👍

**Comment by osm0sis** [comment]
Looks like b229c73 removes the need for a common script, so closing. 👍

**Pull request closed without merging**
