### PR TITLE
Update for BusyBox 1.36.1

### PR DESCRIPTION
**Pull request by osm0sis**
- remove upstreamed/resolved patches
- rebase patches over released stable 1.36.1
- fix KBuild parsing of .S files for Android.mk
- add new patch to fix direct loopback mount and losetup next loop
- switch to recommending the Magisk SELinux fork to ensure Android compatibility

### CODE REVIEW

**Comment by osm0sis** [comment]
Waiting on the tag/version bump to be pushed, which was missed by the busybox maintainer:
https://bugs.busybox.net/show_bug.cgi?id=15596
https://git.busybox.net/busybox/tree/?h=1_36_stable

But the news item and source archive are available and match the 1_36_stable branch except for the version bump, so all should be good once it's out:
https://busybox.net/

**Comment by osm0sis** [comment]
They pushed the Bump commit/tag, and I created the patches one more time over that just to be correct. Should be good now! 🙂

**Comment by osm0sis** [comment]
One final force-push to fix loop mounts on kernels < 5.x; the new TRY_LOOP_CONFIGURE is supposed to fallback gracefully, but something doesn't work correctly, even with my new patch, so update config options to revert to old behavior.

**Comment by liwenjie119** [comment]
when build with the newest Sources in [README.md](https://github.com/topjohnwu/ndk-box-kitchen/blob/update/1_36_1/README.md), it report some error :

```
[armeabi-v7a] StaticLibrary  : libpcre2.a
[armeabi-v7a] Executable     : busybox
ld: error: undefined symbol: hashtab_create
>>> referenced by label_file.c:114 (jni/selinux/libselinux/src/label_file.c:114)
>>>               lto.tmp:(mkswap_main)

ld: error: undefined symbol: hashtab_insert
>>> referenced by label_file.c:130 (jni/selinux/libselinux/src/label_file.c:130)
>>>               lto.tmp:(mkswap_main)

ld: error: undefined symbol: hashtab_search
>>> referenced by label_file.c:135 (jni/selinux/libselinux/src/label_file.c:135)
>>>               lto.tmp:(mkswap_main)

ld: error: undefined symbol: hashtab_destroy_key
>>> referenced by label_file.c:164 (jni/selinux/libselinux/src/label_file.c:164)
>>>               lto.tmp:(mkswap_main)
>>> referenced by label_file.c:124 (jni/selinux/libselinux/src/label_file.c:124)
>>>               lto.tmp:(mkswap_main)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/user/android-ndk-r25c/build/core/build-binary.mk:670: obj/local/armeabi-v7a/busybox] Error 1
```

**Comment by osm0sis** [comment]
Built back when I did it; will need to try it again.

I've just gotten a report today that there may be an issue with the SELinux applets not working even though they built correctly, so maybe some build fixes for the upstream libselinux stuff to look into in general... 🤔

Edit: For starters, likely ndk-box-kitchen will now need to switch to using the Magisk SELinux fork, and that may resolve things: https://github.com/topjohnwu/selinux

**Comment by osm0sis** [comment]
Yep, https://github.com/topjohnwu/selinux got things building again. Makes more sense to keep it in sync with that than constantly hoping upstream works. I'll update the README. :+1:

**Review by topjohnwu — APPROVED** [review]

**Comment by osm0sis** [comment]
Oh, @topjohnwu, I didn't expect the merge just yet... there's still some issue with the SELinux applets not working correctly which I'm trying to track down.

E.g. `ls -alZ` doesn't show the contexts like it should, the column is just empty.

**Comment by osm0sis** [comment]
I've tried rolling my NDK back to r23c and SELinux back to 3.3 which were out when we built 1.34.1, and I've tried building 1.34.1 using the latest SELinux and pcre, but none of that gets `ls -alZ` working, so I think it might be pcre at fault.

Edit: Hmm, rolling back to the Magisk submodule commit pcre @ 8e12681 didn't get it working either. I'm at a loss here. 😕

Edit 2: Could it be my switch to a WSL2 env? Hopefully that's the case, and Magisk's busybox will build fine... 🤞

**Comment by topjohnwu** [comment]
@osm0sis I've built the source code along with the Magisk tree and everything is working just fine

**Comment by osm0sis** [comment]
Hmm, weird. The only thing I can think of is that it must be my WSL2 or something. No idea how to debug that, but I'll figure something out. Glad it's working with Magisk at least!

**Comment by osm0sis** [comment]
> @osm0sis I've built the source code along with the Magisk tree and everything is working just fine

@topjohnwu, turns out that was the clue I needed! lto_fix.lds is missing over here so SELinux was broken in anything directly built from ndk-box-kitchen. PR incoming. 🙂

**Pull request merged**
